CREATE TABLE `TblEmployee` (
  `EmployeeId` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EmployeeCode` char(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'EmployeeCode is used as LoginId to login into application.',
  `FirstName` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `MiddleName` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `LastName` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `FullName` varchar(150) COLLATE utf8_unicode_ci GENERATED ALWAYS AS (concat_ws(' ',`FirstName`,nullif(`MiddleName`,''),`LastName`)) VIRTUAL COMMENT 'Generated from firstName, middleName and lastName',
  `Gender` char(6) COLLATE utf8_unicode_ci NOT NULL,
  `MobileNumber` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `AlternateMobileNumber` varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Email` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `AlternateEmail` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `AddressId` int(10) DEFAULT NULL,
  `JobTitleId` int(10) NOT NULL COMMENT 'JobTitle is the position held by an employee.',
  `RoleId` int(10) NOT NULL COMMENT 'Employee role in tha application.',
  `Active` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Default 0, after confirming registration mail link it becomes 1',
  `Archive` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'After marked employee archived the employee could not able to login through application even if active (This is column is only for active confirmation mail link) marked 1',
  `Password` varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ProfilePhoto` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TokenUUID` char(36) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TokenGeneratedDate` datetime DEFAULT NULL,
  `JoiningDate` date NOT NULL,
  `RecordCreated` datetime NOT NULL,
  `RecordUpdated` datetime DEFAULT NULL,
  PRIMARY KEY (`EmployeeId`),
  UNIQUE KEY `UK_EmployeeCode` (`EmployeeCode`),
  UNIQUE KEY `UK_Email` (`Email`),
  UNIQUE KEY `UK_MobileNumber` (`MobileNumber`),
  UNIQUE KEY `UK_TokenUUID` (`TokenUUID`),
  UNIQUE KEY `UK_ProfilePhoto` (`ProfilePhoto`),
  KEY `idxFK_AddressId` (`AddressId`),
  KEY `idxFK_JobTitleId` (`JobTitleId`),
  KEY `idxFK_RoleId` (`RoleId`),
  CONSTRAINT `FK_TblEmployee_AddressId` FOREIGN KEY (`AddressId`) REFERENCES `TblEmployeeAddress` (`AddressId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_TblEmployee_JobTitleId` FOREIGN KEY (`JobTitleId`) REFERENCES `TblJobTitle` (`JobTitleId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_TblEmployee_RoleId` FOREIGN KEY (`RoleId`) REFERENCES `TblEmployeeRole` (`RoleId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Employee Details';
